@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
@startuml
actor "Player" as PLAYER
participant ":BuyTrainUI" as UI
participant ":BuyTrainController" as BTC
participant "Repositories" as REPOS
participant "repositories\n:Repositories" as REPOS_SINGLETON
participant "scenarioRepository\n:ScenarioRepository" as SCENARIO_REPO
participant "locomotiveRepository\n:LocomotiveRepository" as LOC_REPO
participant "trainRepository\n:TrainRepository" as TRAIN_REPO
participant "playerRepository\n:PlayerRepository" as PLAYER_REPO
participant "appSession\n:ApplicationSession" as APP_SESSION
participant "currentSession\n:UserSession" as CURRENT_SESSION
participant "player\n:Player" as PLAYER_ENTITY
participant "train\n:Train" as TRAIN

activate PLAYER

        PLAYER -> UI : asks to buy a train
        activate UI
            UI --> BTC : buyTrain()
            activate BTC
                BTC -> REPOS : getInstance()
                activate REPOS
                    REPOS --> BTC: repositories
                deactivate REPOS

                BTC -> REPOS_SINGLETON : getScenarioRepository()
                                activate REPOS_SINGLETON
                                    REPOS_SINGLETON --> BTC: scenarioRepository
                                deactivate REPOS_SINGLETON

                BTC -> REPOS_SINGLETON : getLocomotiveRepository()
                activate REPOS_SINGLETON
                    REPOS_SINGLETON --> BTC: locomotiveRepository
                deactivate REPOS_SINGLETON

                BTC -> SCENARIO_REPO : getCurrentScenario() ???
                activate SCENARIO_REPO
                     SCENARIO_REPO -> BTC : scenario
                deactivate SCENARIO_REPO

                BTC -> LOC_REPO : locomotiveRepository.getAvailableLocomotives(scenario)
                activate LOC_REPO
                    LOC_REPO --> BTC : List<Locomotive>
                deactivate LOC_REPO

                BTC --> UI : display available locomotives
            deactivate BTC

            UI --> PLAYER : shows available locomotives and asks for selection
        deactivate UI

    PLAYER -> UI : selects a locomotive
    activate UI
        UI --> PLAYER : requests confirmation
    deactivate UI

    PLAYER -> UI : confirms selection
    activate UI
        UI --> BTC : trainPurchase(locomotive)
       activate BTC
               BTC -> APP_SESSION: getInstance()
                       activate APP_SESSION
                           APP_SESSION --> BTC: appSession
                       deactivate APP_SESSION

                       BTC -> APP_SESSION: appSession.getCurrentSession()
                       activate APP_SESSION
                           APP_SESSION --> BTC: currentSession
                       deactivate APP_SESSION

                       BTC -> CURRENT_SESSION: currentSession.getUserEmail()
                       activate CURRENT_SESSION
                           CURRENT_SESSION --> BTC: email
                       deactivate CURRENT_SESSION

                       BTC -> PLAYER_REPO: getPlayerByEmail(email)
                       activate PLAYER_REPO
                           PLAYER_REPO --> BTC: player
                       deactivate PLAYER_REPO
               BTC -> PLAYER_ENTITY : player.deductPriceFromBudget(locomotive.getPrice())
               activate PLAYER_ENTITY
               PLAYER_ENTITY --> BTC : true
               deactivate PLAYER_ENTITY

               BTC -> TRAIN_REPO : createNewTrain(locomotive)
                       activate TRAIN_REPO
                           TRAIN_REPO -> TRAIN : Train(id, locomotive)
                           activate TRAIN
                               TRAIN --> TRAIN_REPO : train
                               deactivate TRAIN
                               TRAIN_REPO --> BTC : train
                       deactivate TRAIN_REPO

               BTC -> TRAIN_REPO : addTrainToPlayer(player, train)
               activate TRAIN_REPO
                   TRAIN_REPO --> BTC : true
               deactivate TRAIN_REPO

            BTC --> UI : success message
        deactivate BTC

        UI --> PLAYER : display operation success
    deactivate UI

deactivate PLAYER
@enduml