@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

'left to right direction

skinparam classAttributeIconSize 0

hide circle
hide methods

'title Domain Model

class Player {
    name
    budget
}

class Train {
    id
    locomotive
}

class Locomotive {
    model
    power
    acceleration
    topSpeed
    startYear
    acquisitionPrice
}

class Scenario {
    name
    availableLocomotives
    currentDate
}

Train "1" - "1" Locomotive : consists of
Player "1" -- "*" Train : can purchase and own
Scenario "1" -- "*" Locomotive : defines available


@enduml