@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "Player" as Player
participant ":System" as System

activate Player

Player -> System : Requests to build a railway line
activate System

System --> Player : Displays a list of registered stations and asks to select one
deactivate System

Player -> System : Selects a station
activate System

System --> Player : Displays again the list of registered stations and asks to select another one
deactivate System

Player -> System : Selects station again
activate System

System --> Player : Ask to confirm the selected stations to build the railway line
deactivate System

Player -> System : Confirm choices
activate System

System --> Player : Operation successfull!

@enduml